fix: handle empty name in log details avatar
Sanmeet007/logger pull request #10
Opened 2024-07-31 16:23 UTC by HarshitKumar9030

Fixed!

2024-07-31 16:30 UTC, Sanmeet007 commented on lib/components/log_details.dart
Instead of full 'Unknown' string in avatar use just '?' 

```dart
 name.isNotEmpty ? name[0] : 'Unknown',
```

2024-07-31 16:32 UTC, Sanmeet007 requested changes
Instead of full 'Unknown' string in avatar use just '?' 

```dart
 name.isNotEmpty ? name[0] : 'Unknown',
```

2024-07-31 19:38 UTC, HarshitKumar9030 commented
Nice app tho! I was looking for something like this for getting the logs, I actually wanna have them on a server to process further this will be a great starting point!

2024-08-01 02:55 UTC, Sanmeet007 approved these changes

2024-08-01 02:55 UTC, merged

2024-08-01 02:59 UTC, Sanmeet007 commented
Hi @HarshitKumar9030 
Thank you for spotting the bug and fixing it! Your contribution is greatly appreciated and will help improve the overall quality of the project.

Thanks again for your help!